/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/carbonql/networkcontroller/pkg/apis/networkcontroller/v1alpha1"
	scheme "github.com/carbonql/networkcontroller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AssertsGetter has a method to return a AssertInterface.
// A group's client should implement this interface.
type AssertsGetter interface {
	Asserts(namespace string) AssertInterface
}

// AssertInterface has methods to work with Assert resources.
type AssertInterface interface {
	Create(*v1alpha1.Assert) (*v1alpha1.Assert, error)
	Update(*v1alpha1.Assert) (*v1alpha1.Assert, error)
	UpdateStatus(*v1alpha1.Assert) (*v1alpha1.Assert, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Assert, error)
	List(opts v1.ListOptions) (*v1alpha1.AssertList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Assert, err error)
	AssertExpansion
}

// asserts implements AssertInterface
type asserts struct {
	client rest.Interface
	ns     string
}

// newAsserts returns a Asserts
func newAsserts(c *NetworkcontrollerV1alpha1Client, namespace string) *asserts {
	return &asserts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the assert, and returns the corresponding assert object, and an error if there is any.
func (c *asserts) Get(name string, options v1.GetOptions) (result *v1alpha1.Assert, err error) {
	result = &v1alpha1.Assert{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("asserts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Asserts that match those selectors.
func (c *asserts) List(opts v1.ListOptions) (result *v1alpha1.AssertList, err error) {
	result = &v1alpha1.AssertList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("asserts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested asserts.
func (c *asserts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("asserts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a assert and creates it.  Returns the server's representation of the assert, and an error, if there is any.
func (c *asserts) Create(assert *v1alpha1.Assert) (result *v1alpha1.Assert, err error) {
	result = &v1alpha1.Assert{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("asserts").
		Body(assert).
		Do().
		Into(result)
	return
}

// Update takes the representation of a assert and updates it. Returns the server's representation of the assert, and an error, if there is any.
func (c *asserts) Update(assert *v1alpha1.Assert) (result *v1alpha1.Assert, err error) {
	result = &v1alpha1.Assert{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("asserts").
		Name(assert.Name).
		Body(assert).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *asserts) UpdateStatus(assert *v1alpha1.Assert) (result *v1alpha1.Assert, err error) {
	result = &v1alpha1.Assert{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("asserts").
		Name(assert.Name).
		SubResource("status").
		Body(assert).
		Do().
		Into(result)
	return
}

// Delete takes name of the assert and deletes it. Returns an error if one occurs.
func (c *asserts) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("asserts").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *asserts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("asserts").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched assert.
func (c *asserts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Assert, err error) {
	result = &v1alpha1.Assert{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("asserts").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
