/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/carbonql/networkcontroller/pkg/apis/networkcontroller/v1alpha1"
	scheme "github.com/carbonql/networkcontroller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DNSAssertsGetter has a method to return a DNSAssertInterface.
// A group's client should implement this interface.
type DNSAssertsGetter interface {
	DNSAsserts(namespace string) DNSAssertInterface
}

// DNSAssertInterface has methods to work with DNSAssert resources.
type DNSAssertInterface interface {
	Create(*v1alpha1.DNSAssert) (*v1alpha1.DNSAssert, error)
	Update(*v1alpha1.DNSAssert) (*v1alpha1.DNSAssert, error)
	UpdateStatus(*v1alpha1.DNSAssert) (*v1alpha1.DNSAssert, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DNSAssert, error)
	List(opts v1.ListOptions) (*v1alpha1.DNSAssertList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DNSAssert, err error)
	DNSAssertExpansion
}

// dNSAsserts implements DNSAssertInterface
type dNSAsserts struct {
	client rest.Interface
	ns     string
}

// newDNSAsserts returns a DNSAsserts
func newDNSAsserts(c *NetworkcontrollerV1alpha1Client, namespace string) *dNSAsserts {
	return &dNSAsserts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dNSAssert, and returns the corresponding dNSAssert object, and an error if there is any.
func (c *dNSAsserts) Get(name string, options v1.GetOptions) (result *v1alpha1.DNSAssert, err error) {
	result = &v1alpha1.DNSAssert{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsasserts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DNSAsserts that match those selectors.
func (c *dNSAsserts) List(opts v1.ListOptions) (result *v1alpha1.DNSAssertList, err error) {
	result = &v1alpha1.DNSAssertList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsasserts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dNSAsserts.
func (c *dNSAsserts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dnsasserts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a dNSAssert and creates it.  Returns the server's representation of the dNSAssert, and an error, if there is any.
func (c *dNSAsserts) Create(dNSAssert *v1alpha1.DNSAssert) (result *v1alpha1.DNSAssert, err error) {
	result = &v1alpha1.DNSAssert{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dnsasserts").
		Body(dNSAssert).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dNSAssert and updates it. Returns the server's representation of the dNSAssert, and an error, if there is any.
func (c *dNSAsserts) Update(dNSAssert *v1alpha1.DNSAssert) (result *v1alpha1.DNSAssert, err error) {
	result = &v1alpha1.DNSAssert{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dnsasserts").
		Name(dNSAssert.Name).
		Body(dNSAssert).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *dNSAsserts) UpdateStatus(dNSAssert *v1alpha1.DNSAssert) (result *v1alpha1.DNSAssert, err error) {
	result = &v1alpha1.DNSAssert{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dnsasserts").
		Name(dNSAssert.Name).
		SubResource("status").
		Body(dNSAssert).
		Do().
		Into(result)
	return
}

// Delete takes name of the dNSAssert and deletes it. Returns an error if one occurs.
func (c *dNSAsserts) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsasserts").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dNSAsserts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsasserts").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dNSAssert.
func (c *dNSAsserts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DNSAssert, err error) {
	result = &v1alpha1.DNSAssert{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dnsasserts").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
