/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/carbonql/networkcontroller/pkg/apis/networkcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAsserts implements AssertInterface
type FakeAsserts struct {
	Fake *FakeNetworkcontrollerV1alpha1
	ns   string
}

var assertsResource = schema.GroupVersionResource{Group: "networkcontroller.carbonql.com", Version: "v1alpha1", Resource: "asserts"}

var assertsKind = schema.GroupVersionKind{Group: "networkcontroller.carbonql.com", Version: "v1alpha1", Kind: "Assert"}

// Get takes name of the assert, and returns the corresponding assert object, and an error if there is any.
func (c *FakeAsserts) Get(name string, options v1.GetOptions) (result *v1alpha1.Assert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(assertsResource, c.ns, name), &v1alpha1.Assert{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Assert), err
}

// List takes label and field selectors, and returns the list of Asserts that match those selectors.
func (c *FakeAsserts) List(opts v1.ListOptions) (result *v1alpha1.AssertList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(assertsResource, assertsKind, c.ns, opts), &v1alpha1.AssertList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AssertList{}
	for _, item := range obj.(*v1alpha1.AssertList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested asserts.
func (c *FakeAsserts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(assertsResource, c.ns, opts))

}

// Create takes the representation of a assert and creates it.  Returns the server's representation of the assert, and an error, if there is any.
func (c *FakeAsserts) Create(assert *v1alpha1.Assert) (result *v1alpha1.Assert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(assertsResource, c.ns, assert), &v1alpha1.Assert{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Assert), err
}

// Update takes the representation of a assert and updates it. Returns the server's representation of the assert, and an error, if there is any.
func (c *FakeAsserts) Update(assert *v1alpha1.Assert) (result *v1alpha1.Assert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(assertsResource, c.ns, assert), &v1alpha1.Assert{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Assert), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAsserts) UpdateStatus(assert *v1alpha1.Assert) (*v1alpha1.Assert, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(assertsResource, "status", c.ns, assert), &v1alpha1.Assert{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Assert), err
}

// Delete takes name of the assert and deletes it. Returns an error if one occurs.
func (c *FakeAsserts) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(assertsResource, c.ns, name), &v1alpha1.Assert{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAsserts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(assertsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AssertList{})
	return err
}

// Patch applies the patch and returns the patched assert.
func (c *FakeAsserts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Assert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(assertsResource, c.ns, name, data, subresources...), &v1alpha1.Assert{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Assert), err
}
