apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: asserts.networkcontroller.carbonql.com
spec:
  group: networkcontroller.carbonql.com
  version: v1alpha1
  names:
    kind: Assert
    plural: asserts
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
